name: CI

on:
  push:
    branches:
      - master

jobs:
  phpunit:
    name: PHPUnit

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: tifabio/lumen-phpunit-action@master